In [9]:
#Question 1
a = [10,11,12,13,14]
first = 11
last= 13

In [10]:
final=[]
addZeros = False
for i in a:
    final.append(i)
    if i == first:
        addZeros = True
    if i == last:
        addZeros = False
    if addZeros:
        final.extend([0,0,0,0,0])
print(final)       
        
        

[10, 11, 0, 0, 0, 0, 0, 12, 0, 0, 0, 0, 0, 13, 14]


In [21]:
#Question 2
arr1 = [1,0,0,0,1,0]
arr2 = [0,0,1,1,0,1]
arr1.sort()
arr2.sort()
ans = (arr1 == arr2)

print(ans)

False


In [29]:
#question3
import numpy as np
print(0 * np.nan)
print(np.nan != np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3*0.1)

nan
True
False
nan
False


In [44]:
#Question 4
import pandas as pd
ser = pd.Series(['amrita', 'school', 'of', 'engineering', 'chennai', 'campus'])
ser.str.capitalize().str.cat(sep=' ')


'Amrita School Of Engineering Chennai Campus'

In [47]:
#Question 5
#1. Addition of two numpy arrays
import numpy as np
a1 = np.array([10,11,12])
a2 = np.array([19,11,22])
out = a1+a2
out

array([29, 22, 34])

In [49]:
#2. Multiplying a matrix
import numpy as np
mat1 = ([1, 6, 5],[3 ,4, 8],[2, 12, 3])
mat2 = ([3, 4, 6],[5, 6, 7],[6,56, 7])
res = np.dot(mat1,mat2)
print(res)


[[ 63 320  83]
 [ 77 484 102]
 [ 84 248 117]]


In [51]:
#3. Identity Matrix
import numpy as np
mat = np.identity(3)
mat

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])